version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=admin
      - SQL_USER=root
      - SQL_PASSWORD=root
      - SQL_HOST=db
      - SQL_PORT=5432

  db:
    image: postgres:12.0-alpine
    volumes:
      - .dbdata_postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=admin
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready"
      interval: 5s
      timeout: 5s
      retries: 5