# Generated by Django 3.1.3 on 2021-04-07 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=191)),
                ('url', models.CharField(max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=191)),
                ('full_name', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('pushed_at', models.DateTimeField(null=True)),
                ('language', models.CharField(blank=True, max_length=191, null=True)),
                ('forks_count', models.IntegerField()),
                ('stargazers_count', models.IntegerField()),
                ('watchers_count', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scan.user')),
            ],
        ),
    ]
