# Generated by Django 3.1.3 on 2021-04-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('company', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('twitter_username', models.CharField(blank=True, max_length=250, null=True)),
                ('public_repos', models.IntegerField()),
                ('public_gists', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
